# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'delivery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'RxSwift'
   pod 'FBSDKLoginKit'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Storage'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for delivery

end
